export const countryLanguageOptions = [
  { country: "Albania", languages: ["Albanian","English"] },
  { country: "American Samoa", languages: ["English","Spanish"] },
  { country: "Andorra", languages: ["English","Spanish"] },
  { country: "Angola", languages: ["English","Portuguese"] },
  { country: "Anguilla", languages: ["English","Spanish"] },
  { country: "Argentina", languages: ["English","Spanish"] },
  { country: "Aruba", languages: ["English","Spanish"] },
  { country: "Australia", languages: ["English"] },
  { country: "Austria", languages: ["English","German"] },
  { country: "Azerbaijan", languages: ["Azerbaijani","English","Russian"] },
  { country: "Bahamas", languages: ["English","Spanish"] },
  { country: "Baltics", languages: ["English","Estonian","Latvian","Lithuanian"] },
  { country: "Bangladesh", languages: ["English"] },
  { country: "Belgium", languages: ["Dutch","English","French"] },
  { country: "Benin", languages: ["English","French"] },
  { country: "Bolivia", languages: ["Spanish"] },
  { country: "BONAIRE", languages: ["English","Spanish"] },
  { country: "Bosnia and Herzegovina", languages: ["English","Serbian"] },
  { country: "Botswana", languages: ["English"] },
  { country: "Brazil", languages: ["English","Portuguese","Spanish"] },
  { country: "Brunei Darussalam", languages: ["English","Malay"] },
  { country: "Bulgaria", languages: ["Bulgarian","English"] },
  { country: "Burkina Faso", languages: ["English","French"] },
  { country: "Burundi", languages: ["English"] },
  { country: "Cambodia", languages: ["English","Khmer"] },
  { country: "Cameroon", languages: ["English","French"] },
  { country: "Canada", languages: ["English","French"] },
  { country: "Cape Verde", languages: ["English","French"] },
  { country: "Central African Republic", languages: ["English"] },
  { country: "Chad", languages: ["English"] },
  { country: "Chile", languages: ["Spanish"] },
  { country: "Colombia", languages: ["Spanish"] },
  { country: "Cote d\u0027Ivoire (Ivory Coast)", languages: ["English","French"] },
  { country: "Croatia", languages: ["Croatian","English"] },
  { country: "Curacao", languages: ["English","Spanish"] },
  { country: "Cyprus", languages: ["English","Greek"] },
  { country: "Czech Republic", languages: ["Czech","English"] },
  { country: "Democratic Republic of Congo", languages: ["French"] },
  { country: "Denmark", languages: ["Danish","English"] },
  { country: "Dominican Republic", languages: ["English","Spanish"] },
  { country: "Ecuador", languages: ["English","Spanish"] },
  { country: "El Salvador", languages: ["Spanish"] },
  { country: "Equatorial Guinea", languages: ["English"] },
  { country: "Eritrea", languages: ["English"] },
  { country: "Federated States of Micronesia", languages: ["English","Spanish"] },
  { country: "Fiji", languages: ["English"] },
  { country: "Finland", languages: ["English","Finnish","Swedish"] },
  { country: "France", languages: ["Arabic","French"] },
  { country: "French Guiana", languages: ["Arabic","French"] },
  { country: "Gabon", languages: ["English","French"] },
  { country: "Gambia", languages: ["English","French"] },
  { country: "Georgia", languages: ["English","Georgian"] },
  { country: "Germany", languages: ["English","German"] },
  { country: "Ghana", languages: ["English"] },
  { country: "Gibraltar", languages: ["English","Spanish"] },
  { country: "Greece", languages: ["English","Greek"] },
  { country: "Guadeloupe", languages: ["Arabic","French"] },
  { country: "Guam", languages: ["English","Spanish"] },
  { country: "Guatemala", languages: ["Spanish"] },
  { country: "Guinea", languages: ["English","French"] },
  { country: "Guinea-Bissau", languages: ["English","French"] },
  { country: "Guyana", languages: ["English","Spanish"] },
  { country: "Honduras", languages: ["Spanish"] },
  { country: "Hong Kong", languages: ["Chinese","English"] },
  { country: "Hungary", languages: ["Albanian","Bosnia","English","Hungarian","Montenegrin"] },
  { country: "Iceland", languages: ["English"] },
  { country: "India", languages: ["English"] },
  { country: "Indonesia", languages: ["English"] },
  { country: "Iraq", languages: ["Arabic","English","Kurdish"] },
  { country: "Ireland", languages: ["English"] },
  { country: "Israel", languages: ["English","Hebrew"] },
  { country: "Italy", languages: ["English","Italian"] },
  { country: "Japan", languages: ["English","Japanese"] },
  { country: "Kazakhstan", languages: ["English","Kazakh","Russian"] },
  { country: "Kenya", languages: ["English"] },
  { country: "Kosovo", languages: ["Albanian","English"] },
  { country: "Kyrgyzstan", languages: ["English","Kyrgyz","Russian"] },
  { country: "Lesotho", languages: ["English"] },
  { country: "Luxembourg", languages: ["English","French"] },
  { country: "Madagascar", languages: ["French"] },
  { country: "Malawi", languages: ["English"] },
  { country: "Malaysia", languages: ["English","Malay"] },
  { country: "Mali", languages: ["English","French"] },
  { country: "Malta", languages: ["English","Italian"] },
  { country: "Martinique", languages: ["Arabic","French"] },
  { country: "Mauritania", languages: ["English","French"] },
  { country: "Mauritius", languages: ["Arabic","French"] },
  { country: "Mexico", languages: ["English","Spanish"] },
  { country: "Moldova", languages: ["English","Romanian"] },
  { country: "Mongolia", languages: ["English","Mongolian"] },
  { country: "Montenegro", languages: ["English","Serbian"] },
  { country: "Morocco", languages: ["French"] },
  { country: "Mozambique", languages: ["English"] },
  { country: "Namibia", languages: ["English"] },
  { country: "Netherlands", languages: ["Dutch","English"] },
  { country: "Netherlands Antilles", languages: ["English","Spanish"] },
  { country: "New Caledonia", languages: ["English"] },
  { country: "New Zealand", languages: ["English"] },
  { country: "Niger", languages: ["English","French"] },
  { country: "Nigeria", languages: ["English"] },
  { country: "North Macedonia", languages: ["English","F.Y.R.O.Macedonia"] },
  { country: "Northern Ireland", languages: ["English"] },
  { country: "Norway", languages: ["English","Norwegian"] },
  { country: "Pakistan", languages: ["English"] },
  { country: "Panama", languages: ["Spanish"] },
  { country: "Papua New Guinea", languages: ["English"] },
  { country: "Paraguay", languages: ["Spanish"] },
  { country: "Peru", languages: ["Spanish"] },
  { country: "Philippines", languages: ["English"] },
  { country: "Poland", languages: ["English","Polish"] },
  { country: "Portugal", languages: ["English","Portuguese"] },
  { country: "Puerto Rico", languages: ["English","Spanish"] },
  { country: "Qatar", languages: ["Arabic","English"] },
  { country: "Republic of Congo", languages: ["French"] },
  { country: "Reunion Islands", languages: ["Arabic","French"] },
  { country: "Romania", languages: ["English","Romanian"] },
  { country: "Russia", languages: ["English","Russian"] },
  { country: "Rwanda", languages: ["English"] },
  { country: "Saba", languages: ["English","Spanish"] },
  { country: "Saint Eustastius", languages: ["English","Spanish"] },
  { country: "Saint Lucia", languages: ["English","Spanish"] },
  { country: "Saint-Barthélemy", languages: ["English","Spanish"] },
  { country: "Samoa", languages: ["English","Spanish"] },
  { country: "Saudi Arabia", languages: ["Arabic","English"] },
  { country: "Senegal", languages: ["English","French"] },
  { country: "Serbia", languages: ["English","Serbian"] },
  { country: "Sierra Leone", languages: ["English"] },
  { country: "Singapore", languages: ["English"] },
  { country: "Slovak Republic", languages: ["English","Slovak"] },
  { country: "Slovenia", languages: ["English","Hungarian","Slovenian"] },
  { country: "South Africa", languages: ["English"] },
  { country: "South Korea", languages: ["Korean"] },
  { country: "Spain", languages: ["English","Spanish"] },
  { country: "St. Maarten", languages: ["English"] },
  { country: "Suriname", languages: ["English","Spanish"] },
  { country: "Swaziland", languages: ["English"] },
  { country: "Sweden", languages: ["English","Swedish"] },
  { country: "Switzerland", languages: ["English","French","German","Italian"] },
  { country: "Taiwan", languages: ["Chinese","English"] },
  { country: "Tanzania, United Republic of", languages: ["English"] },
  { country: "Thailand", languages: ["English","Thai"] },
  { country: "Togo", languages: ["English","French"] },
  { country: "Tunisia", languages: ["French"] },
  { country: "Turkey", languages: ["English","Turkish"] },
  { country: "Uganda", languages: ["English"] },
  { country: "Ukraine", languages: ["English","Ukrainian"] },
  { country: "United Arab Emirates", languages: ["Arabic","English"] },
  { country: "United Kingdom", languages: ["English"] },
  { country: "United States", languages: ["English","Spanish"] },
  { country: "Uruguay", languages: ["English","Spanish"] },
  { country: "Uzbekistan", languages: ["English","Russian","Uzbek"] },
  { country: "Vanuatu", languages: ["English"] },
  { country: "Vietnam", languages: ["Vietnamese"] },
  { country: "Zambia", languages: ["English"] },
  { country: "Zimbabwe", languages: ["English"] },
];

